-- https://school.programmers.co.kr/learn/courses/30/lessons/276034

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON S.CODE & D.SKILL_CODE = S.CODE
WHERE S.NAME = 'PYTHON' OR S.NAME = 'C#'
-- WHERE S.CODE IN (256, 1024)
ORDER BY D.ID;


